version: '3'

services:
  amazon-crawler:
    build:
      context: .
      dockerfile: Dockerfile
    image: amazon-crawler:latest
    container_name: amazon-crawler
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
    command: ["./amazon-crawler", "-c", "config.yaml"] 