version: '3'

services:
  amazon-crawler:
    image: justincnn/amazon-crawler:latest
    container_name: amazon-crawler
    restart: unless-stopped
    ports:
      - "8899:8899"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
    command: ["./amazon-crawler", "-c", "config.yaml"] 